SELECT 
    A.ID, 
    CASE 
        WHEN ISNULL(B.CHILD_COUNT) THEN 0 # 0인 경우를 대비하기 위해서 LEFT JOIN까지
        ELSE B.CHILD_COUNT
    END AS CHILD_COUNT
FROM 
    ECOLI_DATA A
LEFT JOIN 
    # ID에 대한 자식수 서브쿼리
    (SELECT PARENT_ID AS ID, COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID) B ON A.ID = B.ID
ORDER BY A.ID;