SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    TRUNCATE(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND TRUNCATE(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) >= 500000
    AND TRUNCATE(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) < 2000000
    AND C.CAR_ID NOT IN (
        SELECT 
            CAR_ID 
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            (START_DATE < '2022-11-30' AND END_DATE > '2022-11-01')
    )
ORDER BY 
    FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;