WITH A 
    AS (SELECT 
            YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS M
        FROM 
            ECOLI_DATA
        GROUP BY 
            YEAR(DIFFERENTIATION_DATE))
            
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (A.M - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID
FROM
    A
JOIN
    ECOLI_DATA E
ON 
    A.Y = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY 
    YEAR, YEAR_DEV