SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (T.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,  # 최댓값에서 편차구하기
    E.ID
FROM 
    ECOLI_DATA E
JOIN 
    # 년도 추출, 년도별 최댓값 서브쿼리 작성
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)) T ON YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
ORDER BY 
    YEAR, YEAR_DEV;
