SELECT 
       EXTRACT(YEAR  FROM OS.SALES_DATE)  AS YEAR,
       EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH,
       COUNT(DISTINCT OS.USER_ID)        AS PURCHASED_USERS,
       ROUND(
         COUNT(DISTINCT OS.USER_ID) * 1.0 / 
         (SELECT COUNT(DISTINCT USER_ID)
            FROM USER_INFO
           WHERE EXTRACT(YEAR FROM JOINED) = 2021)
       , 1) AS PURCHASED_RATIO
  FROM USER_INFO UI
  JOIN ONLINE_SALE OS 
    ON UI.USER_ID = OS.USER_ID
 WHERE EXTRACT(YEAR FROM UI.JOINED) = 2021
 GROUP BY EXTRACT(YEAR  FROM OS.SALES_DATE),
          EXTRACT(MONTH FROM OS.SALES_DATE)
 ORDER BY EXTRACT(YEAR  FROM OS.SALES_DATE),
          EXTRACT(MONTH FROM OS.SALES_DATE);