SELECT 
    A.ID, 
    CASE
        WHEN B.PCT > 0.75 THEN 'LOW'
        WHEN B.PCT > 0.5 THEN 'MEDIUM'
        WHEN B.PCT > 0.25 THEN 'HIGH'
        ELSE'CRITICAL'
    END AS COLONY_NAME
FROM 
    ECOLI_DATA A
JOIN 
    (SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PCT
     FROM ECOLI_DATA) B ON A.ID = B.ID
ORDER BY A.ID;