SELECT 
    ID, EMAIL, FIRST_NAME, LAST_NAME
FROM 
    DEVELOPERS
WHERE 
    # 서브쿼리에 속하는 ID만
    ID IN (SELECT DISTINCT D.ID # 중복 제거
           FROM DEVELOPERS D 
           JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE # 비트 연산
           WHERE S.NAME = 'C#' OR S.NAME = 'Python')
ORDER BY ID