WITH A 
    AS (SELECT H.HISTORY_ID, R.CAR_TYPE, R.DAILY_FEE, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION # 대여한 날 반납해도 1일이니까
        FROM 
            CAR_RENTAL_COMPANY_CAR R 
        JOIN 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        ON 
            R.CAR_ID = H.CAR_ID
        WHERE
            R.CAR_TYPE = '트럭')
            
        
SELECT 
    A.HISTORY_ID,
    ROUND((1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100)) * A.DAILY_FEE * A.DURATION , 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
RIGHT JOIN  # DURATION_TYPE이 없는 경우가 있을 수 있음
    A
ON 
    D.CAR_TYPE = A.CAR_TYPE
    AND (CASE 
            WHEN A.DURATION >= 90 THEN '90일 이상'
            WHEN A.DURATION BETWEEN 30 AND 89 THEN '30일 이상'
            WHEN A.DURATION BETWEEN 7 AND 29 THEN '7일 이상'
            ELSE '-'
        END = D.DURATION_TYPE)
ORDER BY
    FEE DESC, A.HISTORY_ID DESC;