SELECT 
    I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM 
    ITEM_INFO I
WHERE 
    # NOT IN은 AND연산으로 NULL이 들어가면 NULL을 반환!!
    I.ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID
                      FROM ITEM_TREE
                      WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY 
    I.ITEM_ID DESC;