-- 코드를 작성해주세요
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I, FISH_NAME_INFO N 
WHERE I.FISH_TYPE = N.FISH_TYPE
AND I.LENGTH = (
    SELECT MAX(I2.LENGTH)
    FROM FISH_INFO I2 
    WHERE I2.FISH_TYPE = I.FISH_TYPE
)
ORDER BY I.ID;